language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install: "pip install coverage unittest2"
script: "nosetests --with-coverage --cover-package=glmpca"
branches:
  only:
    - master